# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "zergling" do |zergling|

    zergling.vm.box = "generic/ubuntu2204"
    # zergling.vm.box = "generic/fedora26"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # Using IPs on the WSL switch subnet.
    # zergling.vm.network "private_network"

    # Provider-specific zerglinguration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    
    # zergling.vm.provider "virtualbox" do |vb|
    #   vb.memory = "2048"
    #   vb.cpus = 2
    # end

    zergling.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
      libvirt.connect_via_ssh = false
    end

    zergling.vm.provision "shell", path: "provision.sh"
  end
end

