# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "zergling" do |zergling|

    zergling.vm.box = "generic/ubuntu2204"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # Using IPs on the WSL switch subnet.
    # zergling.vm.network "private_network"

    # Provider-specific zerglinguration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    zergling.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    zergling.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
      libvirt.connect_via_ssh = false
    end

  end

end

