# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./vagrant_data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y upgrade
  SHELL

  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2004"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.66.66.10"

    master.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
    end
  end

  config.vm.define "worker-1" do |worker1|
    worker1.vm.box = "generic/ubuntu2004"
    worker1.vm.hostname = "worker-1"
    worker1.vm.network "private_network", ip: "10.66.66.11"

    worker1.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end
  end

  config.vm.define "worker-2" do |worker2|
    worker2.vm.box = "generic/ubuntu2004"
    worker2.vm.hostname = "worker-2"
    worker2.vm.network "private_network", ip: "10.66.66.12"

    worker2.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end
  end

end
