- hosts:
  - all
  become: true
  tasks:
  - import_role:
      name: "igor_nikiforov.docker"
    tags: ["install_docker"]
    vars:
      docker_daemon_config:
        bip: "10.10.11.1/24"
        default-address-pools:
        - base: "10.11.0.0/16"
          size: 24
  - import_role:
      name: ./roles/prepare_k8s_node
    tags: ["prepare_k8s"]
