- hosts:
  - all
  become: true
  tasks:

  - name: Install docker
    import_role:
      name: igor_nikiforov.docker
      # name: /home/voje/git/ansible-role-docker
    tags: ["install_docker"]
    vars:
      docker_install: true
      docker_version: latest
      docker_daemon_config:
        bip: "10.10.11.1/24"
        default-address-pools:
        - base: "10.11.0.0/16"
          size: 24
      docker_service_enabled: true
      docker_users: vagrant

  - name: Prepare k8snode
    import_role:
      name: ./roles/prepare_k8s_node
    tags: ["prepare_k8s_node"]

