---
# tasks file for kubeadmin_install
- name: Load br_netfilter module
  lineinfile:
    create: true
    path: /etc/modules-load.d/k8s.conf
    line: "br_netfilter"

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Enable processing of IP packets traversing bridges by iptables
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: true
    sysctl_set: true
  with_items:
  - net.bridge.bridge-nf-call-ip6tables
  - net.bridge.bridge-nf-call-iptables

- name: Install k8s binaries
  debug:
    msg: "TODO"
