# Following blogpost:
# https://computingforgeeks.com/install-mirantis-cri-dockerd-as-docker-engine-shim-for-kubernetes/
---
- name: Shell from tutorial
  shell: |
    VER=$(curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest|grep tag_name | cut -d '"' -f 4|sed 's/v//g')
    echo $VER
    ### For Intel 64-bit CPU ###
    wget https://github.com/Mirantis/cri-dockerd/releases/download/v${VER}/cri-dockerd-${VER}.amd64.tgz
    tar xvf cri-dockerd-${VER}.amd64.tgz
    mv cri-dockerd/cri-dockerd /usr/local/bin/
    cri-dockerd --version

- name: Prepare systemd service
  shell: |
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
    mv cri-docker.socket cri-docker.service /etc/systemd/system/
    sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

- name: Start daemon
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: "{{ item }}"
  with_items:
  - cri-docker.service
  - cri-docker.socket