- hosts:
  - all
  tasks:

  - name: Install docker
    become: true
    import_role:
      name: igor_nikiforov.docker
      # name: /home/voje/git/ansible-role-docker
    tags: ["install_docker"]
    vars:
      docker_install: true
      docker_version: latest
      docker_daemon_config:
        bip: "10.10.11.1/24"
        default-address-pools:
        - base: "10.11.0.0/16"
          size: 24
      docker_service_enabled: true
      docker_users: ["vagrant"]

  - name: Prepare k8snode
    become: true
    import_role:
      name: ./roles/prepare_k8s_node
    tags: ["prepare_k8s_node"]

#   - name: Install GoLang
#     import_role:
#       name: gantsign.golang
#     tags: ["install_golang"]

# unix:///var/run/cri-dockerd.sock
# systemd is recommended for Kubeadm-based setups
  - name: Install Docker shim
    become: true
    import_tasks: ./install_cri_docker.yaml
    tags: ["install_cri_docker"]
  
  # Run as user
  - name: Prepare kubectl
    import_tasks: ./prepare_kubectl.yaml
    tags: ["prepare_kubectl"]
